<div class="container">
    <h1>Todo List</h1>
  <form action="handler/add_task.php" method="POST" class="todo-container">
        <input type="text" id="todoInput" name="task" placeholder="Enter your task" required>
        <button class="button" type="submit">Add</button>
    </form>
    <ul id="todoList"></ul>
  </div>

  
  <?php include getcwd().'/components/TodoList.phtml' ?>



  <style>
    body {
  font-family: Arial, sans-serif;
  background-color: #f4f4f4;
  margin: 0;
  padding: 0;
}

.container {
  max-width: 600px;
  margin: 50px auto;
  background-color: #fff;
  padding: 20px;
  border-radius: 8px;
  box-shadow: 0 0 10px rgba(0, 0, 0, 0.1);
}

h1 {
  text-align: center;
}

.todo-container {
  display: flex;
  margin-bottom: 20px;
}

.todo-container input[type="text"] {
  flex: 1;
  padding: 10px;
  font-size: 16px;
}

.todo-container .button {
  padding: 10px 20px;
  background-color: #007bff;
  color: #fff;
  border: none;
  cursor: pointer;
}

.todo-container .button:hover {
  background-color: #0056b3;
}

ul {
  list-style-type: none;
  padding: 0;
}

li {
  background-color: #f9f9f9;
  padding: 10px;
  margin-bottom: 5px;
  border-radius: 5px;
}

li:hover {
  background-color: #e3e3e3;
}

  </style>